Merge pull request #1 from overmindtech/submit-plan
Implement the submit-plan action

GitOrigin-RevId: d3f3d40d9cc72883127e0e8517301af808eb941f

diff --git a/submit-plan/action.yml b/submit-plan/action.yml
--- a/submit-plan/action.yml
+++ b/submit-plan/action.yml
@@ -1,162 +1,37 @@
 name: Submit Terraform plan to Overmind
-author: https://overmind.tech
-branding:
-  color: purple
-  icon: upload-cloud
 description: |
   Uses the Overmind CLI to submit a terraform plan as a new Change to the Overmind API. Results will be posted as a comment on the PR.
 
   Use the `overmindtech/actions/install` action to install the CLI before this.
 
-  This action requires one or more locations of the results of `terraform show -json $TFPLAN_FILE` passed in as `plan-json`. Due to limitations of GitHub Actions, this is a space-separated list, _not_ a YAML array.
-
-  By default this uses the calling PR as Ticket Link for the new Change.
+  This action requires `terraform` to be installed and on the `$PATH`, as well as the modules initialised.
 inputs:
-  ovm-api-key:
-    description: Pass in an Overmind token to give access to your account on Overmind
-  plan-json:
-    description: The location of the terraform plan file (generated from `terraform plan -out=...` and `terraform show -json ...`; defaults to `tfplan.json`). Due to limitations of GitHub Actions, this is a space-separated list, _not_ a YAML array.
+  github_token:
+    description: Pass in a github token to allow posting comments to the PR
+  ovm_token:
+    description: Pass in an overmind token to give access to your account on Overmind
+  plan_file:
+    description: The location of the terraform plan file (generated from `terraform plan -out=...` and `terraform show -json ...`; defaults to `tfplan.json`)
     default: tfplan.json
-  plan-output:
-    description: The location of the terraform plan rendered output (generated from `terraform plan | tee FILE`; defaults to `tfplan.output`).
-    default: tfplan.output
-  log:
-    description: The log level for the job
-    default: info
-  fetch-change:
-    description: Whether or not to fetch the change after submitting it. Set this to 'false' to avoid waiting for risk calculation when no human review is required.
-    default: true
-  number:
-    description: "Pull request number to report results back."
-    default: ${{ github.event.number }}
-  app:
-    description: "The Overmind instance to connect to. Defaults to `https://app.overmind.tech`"
-    required: false
-  tags:
-    description: "A comma separated list of key=value tags to attach to the change"
-    required: false
-
-outputs:
-  change-url:
-    description: "The URL of the created change"
-    value: ${{ steps.submit-plan.outputs.change-url }}
-
-  message:
-    description: "A markdown formatted message describing the current state of the change"
-    value: ${{ steps.submit-plan.outputs.change-url }}
 
 runs:
   using: composite
   steps:
-    - name: Create a Change from a terraform plan
-      id: submit-plan
+    - name: Require to run in a PR
+      shell: bash
+      if: ${{ github.event_name != 'pull_request' }}
+      run: |
+        echo "::error ::Need to run as pull_request, not '${{ github.event_name }}'"
+        exit 1
+
+    - name: Transform plan to json
       shell: bash
       env:
-        OVM_API_KEY: ${{ inputs.ovm-api-key }}
+        OVM_TOKEN: ${{ inputs.ovm_token }}
       run: |
-        set -xe
-
-        declare -a args
-        declare -a chg_args
-
-        # figure out the git change in this event
-        if [ ${{ github.event_name }} = pull_request ]; then
-          base="$(jq -r .pull_request.base.sha < ${{github.event_path}} )"
-          head="$(jq -r .pull_request.head.sha < ${{github.event_path}} )"
-          args+=("--code-changes-diff=./overmindtech/code-changes.diff")
-        elif [ ${{ github.event_name }} = push ]; then
-          base="$(jq -r .before < ${{github.event_path}} )"
-          if [ "$base" = "0000000000000000000000000000000000000000" ]; then
-            # new branch was pushed, default to the repo's default branch as
-            # base for the diff
-            #
-            # Note that this is only the second-worst choice here, as this will
-            # show what's on the default branch, but not in this push as getting
-            # removed, even though a merge would keep it. To avoid _that_, we'd
-            # need to use the `merge-base` between the default branch and the
-            # current branch, but that would inversely _hide_ changes that are
-            # on the default branch but not in this push, making it easier to
-            # miss things for folks with a push-based workflow.
-            base="${{github.repository.default_branch}}"
-          fi
-          head="$(jq -r .after < ${{github.event_path}} )"
-          args+=("--code-changes-diff=./overmindtech/code-changes.diff")
-        fi
-
-        if [ -n "$code_changes_arg" ]; then
-          git fetch --depth=1 origin "$base"
-          git fetch --depth=1 origin "$head"
-          git diff "$base" "$head" > ./overmindtech/code-changes.diff
-        fi
-
-        if [ -f ${{ inputs.plan-output }} ]; then
-          args+=("--terraform-plan-output=${{ inputs.plan-output }}")
-        fi
-
-        if [ -n "${{ inputs.tags }}" ]; then
-          args+=("--tags=${{ inputs.tags }}")
-        fi
-
-        if [ ${{ github.event_name }} = pull_request ]; then
-          title="$(jq -r .pull_request.title < ${{github.event_path}} )"
-          description='This change was automatically created from a PR'
-          ticket_link='${{ github.event.pull_request.html_url }}'
-        else
-          title="Deploying from $(git describe --all --long) by ${{ github.actor }}"
-          if [ "${{ github.triggering_actor }}" != "${{ github.actor }}"]; then
-            title="$title (triggered by ${{ github.triggering_actor }})"
-          fi
-          description='This change was automatically created from Github Actions'
-          ticket_link='${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
-        fi
-
-        if [ -n "${{ inputs.app }}" ]; then
-          args+=("--app=${{ inputs.app }}")
-          chg_args+=("--app=${{ inputs.app }}")
-        fi
-
-        ./overmindtech/overmind changes submit-plan \
-            --title "$title" \
-            --description "$description" \
-            --ticket-link "$ticket_link" \
-            "${args[@]}" \
-            '${{ inputs.plan-json }}' \
-            > ./overmindtech/change-url
-
-        echo "ticket-link=${{ github.event.pull_request.html_url }}" >> $GITHUB_OUTPUT
-        echo "${{ github.event.pull_request.html_url }}" >> ./overmindtech/ticket-link
-        echo "change-url=$(< ./overmindtech/change-url)" >> $GITHUB_OUTPUT
-
-        if [ ${{ inputs.fetch-change }} != "false" ]; then
-          ./overmindtech/overmind changes get-change \
-            --change "$(< ./overmindtech/change-url)" \
-            --format markdown \
-            --log '${{ inputs.log }}' \
-            "${chg_args[@]}" \
-            > ./overmindtech/message
-
-          DELIMITER="$(uuidgen)"
-          echo "message<<$DELIMITER" >> $GITHUB_OUTPUT
-          cat ./overmindtech/message >> $GITHUB_OUTPUT
-          echo "$DELIMITER" >> $GITHUB_OUTPUT
-        fi
-
-    - name: Post change message as sticky comment
-      uses: marocchino/sticky-pull-request-comment@v2
-      if: ${{ steps.submit-plan.outputs.change-url != '' && inputs.fetch-change != 'false' }}
-      with:
-        header: change
-        message: ${{ steps.submit-plan.outputs.message }}
-        number: ${{ inputs.number }}
-
-    - name: Upload change-url as file
-      uses: actions/upload-artifact@v4
-      with:
-        name: overmind-change-url.txt
-        path: ./overmindtech/change-url
-
-    - name: Upload ticket-link as file
-      uses: actions/upload-artifact@v4
-      with:
-        name: overmind-ticket-link.txt
-        path: ./overmindtech/ticket-link
+        set -x
+        ./overmindtech/ovm-cli change-from-tfplan \
+            --title '${{ github.event.pull_request.title }}' \
+            --description 'This change was automatically created from a PR' \
+            --ticket-link '${{ github.event.pull_request.html_url }}' \
+            --tfplan-json '${{ inputs.plan_file }}'
